# Generated by Django 3.0 on 2020-06-09 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('adress', models.CharField(max_length=225)),
                ('phone_number', models.CharField(max_length=225)),
                ('open_time', models.CharField(max_length=225)),
                ('close_time', models.CharField(max_length=225)),
                ('category', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=225)),
                ('time', models.CharField(max_length=225)),
                ('requirements', models.CharField(max_length=225)),
                ('confirmed', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('price', models.IntegerField()),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Shop')),
            ],
        ),
    ]
