# Generated by Django 3.0 on 2020-06-11 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='close_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='open_time',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Shop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='likes',
            field=models.ManyToManyField(related_name='likes', through='app1.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
