# Generated by Django 3.0 on 2020-06-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200611_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
