# Generated by Django 3.0 on 2020-06-19 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='adress',
            new_name='address',
        ),
    ]
