# Generated by Django 3.0 on 2020-06-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200619_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='photo',
            field=models.ImageField(default='', upload_to='images/menu'),
        ),
    ]
